#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes/sonata_admin.yaml

index:
    path:     /{page}
    controller: App\Controller\IndexController::index
    defaults:
        page: 1
    requirements:
        page: '\d+'

category:
    path:     /category/{category_id}/{page}
    controller: App\Controller\CategoryController::index
    defaults:
        category_id: 0
        page: 1
    requirements:
        category_id: '\d+'
        page: '\d+'

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
