#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes/sonata_admin.yaml

index:
    path:     /{page}
    controller: App\Controller\IndexController::index
    defaults:
        page: 1
    requirements:
        page: '\d+'

category:
    path:     /category/{slug}/{page}
    controller: App\Controller\CategoryController::index
    defaults:
        slug: 0
        page: 1
    requirements:
        slug: '[a-z0-9-]+'
        page: '\d+'

post:
    path:     /post/{slug}
    controller: App\Controller\PostController::index
    defaults:
        slug: 0
    requirements:
        slug: '[a-z0-9-]+'

contact:
    path:     /contact
    controller: App\Controller\ContactController::index

contact_mail:
    path:     /contact/mail
    controller: App\Controller\ContactController::mail

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
