# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,EntityManager,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post", label: Category }
        public: true

    admin.blog_post:
        class: App\Admin\BlogPostAdmin
        arguments: [~, App\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post", label: Blog post }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: User }
        public: true

    app.doctrine.hash_password_listener:
        class: App\Doctrine\HashPasswordListener
        arguments: ['@security.password_encoder']
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.category_slug_listener:
        class: App\Doctrine\CategorySlugListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.blog_post_slug_listener:
        class: App\Doctrine\BlogPostSlugListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }



